### ISSUE TITLE
Graphql doesn't support union input types

### ISSUE THREAD

**Issue by robojones** [robojones/gqltest#8]
### Problem
The draft syntax which aims to use the `@expect` directive for all comparable types. This requires the usage of a union type which is not supported by the current graphql syntax.
```graphql
@expect(v: "hello")
@expect(v: 5)
```
This syntax would need `v` to have a union type which contains String and Int.

There are two alternatives to work around the usage of a union type:
### Solution 1: Define the expect directive with an optional parameter for each type
```graphql
directive @expect(string: String, int: Int, float: Float, boolean: Boolean, id: ID)
```
This approach allows the user to use the directive like this:
```graphql
@expect(string: "hello")
```
The problem is that the directive definition would allow the user to specify multiple values:
```graphql
@expect(string: "hello", int: 15)
```
Another problem is that when using variables these could use optional types which is not intended.

### Solution 2: Define separate directives for all the types
```graphql
@expectString(equal: "hello")
@expectInt(equal: 15)
```
This syntax is less good looking but allows for easier verification. The problem here is that the user could use multiple different `@expect*` directives on the same field.

**Comment by steebchen** [comment]
I think solution one is better for the end-user as it's slightly cleaner IMO. However, if you think that using solution 2 makes everything easier on your side, it wouldn't be so bad either.

**Comment by robojones** [comment]
I too think that solution 1 looks better. The problem with it is that later on, when introducing [variables](https://github.com/robojones/gqltest#variables) it would enable the use of optional variable types (`String` instead of `String!`).

Solution 2 on the other hand would enforce required types. In test scenarios you always want to check for a specific value. For me it makes little sense to check: "I expect this field to return the username or nothing at all".

I still don't like solution 2. Does anyone have a better idea?

**Comment by robojones** [comment]
I think I'll go with the second solution.
Especially when adding more comparison features in the future it will be more consistent.
If I implement it like this for now:
```graphql
@expectString(equal: "hello")
```
It will be easy to add more features later on:
```graphql
# match the string against a regular expression
@expectString(match: "[a]sdf")
```

**Comment by steebchen** [comment]
Sounds good!
